- code/app/src/main/res/drawable/ic_add.xml
- code/app/src/main/res/drawable/ic_edit.xml
- code/app/src/main/res/drawable/ic_filter.xml
- code/app/src/main/res/drawable/ic_home.xml
- code/app/src/main/res/drawable/ic_location.xml
- code/app/src/main/res/drawable/profile_placeholder.xml
- code/app/src/main/res/layout/mood_history_block.xml
- code/app/src/main/res/layout/my_profile.xml
- code/app/src/main/res/menu/bottom_nav_menu.xml
- code/app/src/main/res/values/colors.xml
- code/app/src/main/res/values/strings.xml
Added xml files needed for mood history view 
in res/layout 
- mood_history_block.xml 
- my_profile.xml 
in res/drawable 
- ic_add.xml 
- ic_edit.xml 
- ic_filter.xml 
- ic_home.xml 
- ic_loaction.xml 
- profile_placeholder.xml 
in res/menu 
- bottom_nav_menu.xml
> 62 create a mood history view

- code/app/src/main/res/drawable/ic_close.xml
- code/app/src/main/res/drawable/ic_search.xml
- code/app/src/main/res/layout/filter_fragment.xml
- code/app/src/main/res/layout/fragment_first.xml
- code/app/src/main/res/layout/fragment_second.xml
- code/app/src/main/res/values/colors.xml
- code/app/src/main/res/values/strings.xml
added filter_fragment.xml for filtering mood event lists in order to add the textbook specified in the requirement
> added filter fragment

- code/app/src/main/java/com/otmj/otmjapp/EmotionalState.java
Pull requests for emotionalState
> pull request for emotional state

- code/app/src/main/java/com/otmj/otmjapp/EmotionalState.java
- code/app/src/main/java/com/otmj/otmjapp/Models/EmotionalState.java
- code/app/src/main/java/com/otmj/otmjapp/Models/MoodEvent.java
- code/app/src/main/java/com/otmj/otmjapp/Models/SocialSituation.java
> Updated Ethan's initial models to work well with `Entity` and `DatabaseObject` classes

- code/app/src/main/java/com/otmj/otmjapp/Helper/UserManager.java
- code/app/src/main/java/com/otmj/otmjapp/Models/User.java
> `UserManager` bug fixes

- code/app/src/main/java/com/otmj/otmjapp/Models/EmotionalState.java
- code/app/src/main/java/com/otmj/otmjapp/MoodEventAddEditDialogFragment.java
- code/app/src/main/java/com/otmj/otmjapp/TextValidator.java
- code/app/src/main/res/drawable/ic_add_location.xml
- code/app/src/main/res/layout/create_mood_event.xml
- code/app/src/main/res/values/strings.xml
Please Note that the MoodDetailsAddEditFragment is only a rough draft
I can't figure out a logic to get the userID for the MoodEvent constructor so I just set it to 0 by default. 
Adding an image and location will not be implemented until project part 4. 
I made changes in the create_mood_event.xml so that the code for MoodDetailsAddEditFragment is simpler. If you are interested in UI, you can go check it out. 
I also updated EmotionalState.java to have the xml emojis.
> added MoodDetailsAddEditFragment rough draft

- code/app/src/main/java/com/otmj/otmjapp/adapters/FollowersListAdapter.java
- code/app/src/main/res/layout/create_mood_event.xml
- code/app/src/main/res/values/colors.xml
- code/app/src/main/res/values/strings.xml
- code/app/src/main/res/values/styles.xml
error: app: to android: lines within create_mood_event.xml
> 162 - Fixed Error

- code/app/src/main/java/com/otmj/otmjapp/Fragments/TimelineFragment.java
Fix the bug that after click on login or sign up cannot got to Moodswing page
> # branch 192, fix app cannot go to MainActivity bug

- code/app/src/main/java/com/otmj/otmjapp/Adapters/TimelineMoodEventAdapter.java
- code/app/src/main/java/com/otmj/otmjapp/Adapters/UserProfilePageMoodEventAdapter.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/UserProfileFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/UserManager.java
- code/app/src/main/java/com/otmj/otmjapp/Models/EmotionalState.java
- code/app/src/main/java/com/otmj/otmjapp/Models/MoodEvent.java
- code/app/src/main/java/com/otmj/otmjapp/Models/User.java
- code/app/src/main/res/layout/my_mood_history_block.xml
- code/app/src/main/res/layout/my_profile.xml
- code/app/src/main/res/layout/user_profile_view_mood_event_block.xml
User profile page now can display all the mood event the user have, also fix some bugs that existing in model class and handler class
> User profile page now can display all the mood event the user have

- code/app/src/main/java/com/otmj/otmjapp/Fragments/TimelineFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/UserProfileFragment.java
- code/app/src/main/java/com/otmj/otmjapp/MainActivity.java
- code/app/src/main/res/layout/activity_main.xml
- code/app/src/main/res/layout/fragment_timeline.xml
- code/app/src/main/res/menu/for_you_bottom_nav_menu.xml
Now User Profile page does not get highlight all the time, but when at timeLineFragment under add button there is highlight, will fix this later
> fix BottomNavigationView display problem

- code/app/src/main/java/com/otmj/otmjapp/Fragments/TimelineFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/FirestoreDB.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/FollowHandler.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/UserManager.java
- code/app/src/main/java/com/otmj/otmjapp/Models/DatabaseObject.java
- code/gradle/libs.versions.toml
The only thing left to do is to fix the implementation of MoodEventAddEditDialogFragment, then the correct dialog fragment can be shown. More context is provided on line 83 of TimelineFragment.
Once that's been done, allowing the user to edit only the moodEvents they've posted should be straightforward (view line 83 of TimelineFragment)
> Added most of the required functionality to TimelineFragment

- code/app/src/androidTest/java/com/otmj/otmjapp/UserProfilePageTest.java
Finish the testing for User Profile Page
> finish UserProfilePageTest

- code/app/src/main/java/com/otmj/otmjapp/Helper/DBSortOption.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/FirestoreDB.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/MoodEventsManager.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/MoodHistoryFilter.java
> Show mood events in reverse-chronological order

- code/app/src/main/java/com/otmj/otmjapp/Adapters/TimelineMoodEventAdapter.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/MoodEventAddEditDialogFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/MoodEventDetailsFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/CustomImageSpan.java
- code/app/src/main/res/layout/create_mood_event.xml
Max char requirement -> 200 chars 
Fixed emoji formatting in timeline and full details views
> updated max char requirement to 200 chars

- code/app/src/main/java/com/otmj/otmjapp/Fragments/FollowersListFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/TimelineFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/FollowHandler.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/UserManager.java
- code/app/src/main/res/layout/bottom_nav.xml
- code/app/src/main/res/layout/fragment_timeline.xml
- code/app/src/main/res/layout/list_screen.xml
- code/app/src/main/res/navigation/app_nav_graph.xml
Added people you may know page with list of data
> 246 - Added People You May Know Page

- code/app/src/main/AndroidManifest.xml
- code/app/src/main/java/com/otmj/otmjapp/Adapters/FollowersListViewAdapter.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/FollowListFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/FollowersListFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/TimelineFragment.java
- code/app/src/main/java/com/otmj/otmjapp/InitialActivity.java
- code/app/src/main/java/com/otmj/otmjapp/MainActivity.java
- code/app/src/main/res/layout/list_screen.xml
-Added a Search Function for People You May Know
> 247 - Added a Search Function for People You May Know

- code/app/src/main/java/com/otmj/otmjapp/Fragments/FilterFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/TimelineFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/FilterOptions.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/MoodEventsManager.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/MoodHistoryFilter.java
> Filter works completely on timeline page

- code/app/src/main/java/com/otmj/otmjapp/Fragments/FilterFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/UserProfileFragment.java
> Filter button now works in profile page

- code/app/src/main/java/com/otmj/otmjapp/Helper/MoodEventsManager.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/MoodHistoryFilter.java
Call method "getMoodEventsWithLocation" in `MoodEventsManager`. I didn't test it, so let me know if it works
> Get mood events with location

- code/app/src/main/AndroidManifest.xml
- code/app/src/main/java/com/otmj/otmjapp/Adapters/FollowersListViewAdapter.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/FollowListFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/UserProfileFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/FollowHandler.java
- code/app/src/main/res/layout/followed_user_profile_view.xml
- code/app/src/main/res/layout/my_profile.xml
- code/app/src/main/res/layout/unfollowed_user_profile_view.xml
- code/app/src/main/res/navigation/app_nav_graph.xml
Reused xml for profile and added setVisibility values to button elements depending on whether the current user follows the user or not.
Clicking on usernames in following lists navigates to their profile
> 248 - Navigate to user's profile when clicking on username in people you may know list

- code/app/src/main/java/com/otmj/otmjapp/Adapters/TimelineMoodEventAdapter.java
Clicking on the profile image or username on timeline navigates to their profile
> 249 - in the timeline when profile image is clicked navigate to selected user

- code/app/src/main/java/com/otmj/otmjapp/Adapters/TimelineMoodEventAdapter.java
The UI of the timeline is a bit messed up
> Revert "249 - in the timeline when profile image is clicked navigate to selected user"

- code/app/src/main/java/com/otmj/otmjapp/Fragments/TimelineFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/UserProfileFragment.java
- code/app/src/main/res/layout/timeline_mood_event.xml
- code/app/src/main/res/layout/user_block.xml
Debugging something. Will merge again
> Revert "77 - allow users to request to follow each other"

- code/app/src/main/AndroidManifest.xml
- code/app/src/main/java/com/otmj/otmjapp/Adapters/FollowersListViewAdapter.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/FollowListFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/UserProfileFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/FollowHandler.java
- code/app/src/main/res/layout/followed_user_profile_view.xml
- code/app/src/main/res/layout/my_profile.xml
- code/app/src/main/res/layout/unfollowed_user_profile_view.xml
- code/app/src/main/res/navigation/app_nav_graph.xml
Debugging something. Will merge again
> Revert "248 - Navigate to user's profile when clicking on username in people you may know list"

- code/app/src/main/java/com/otmj/otmjapp/Fragments/FollowListFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/MoodEventDetailsFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/UserProfileFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/FollowHandler.java
- code/app/src/main/java/com/otmj/otmjapp/Models/User.java
- code/app/src/main/res/layout/list_screen.xml
- code/app/src/main/res/layout/my_profile.xml
- code/app/src/main/res/navigation/app_nav_graph.xml
I built upon Yves' and Ethan's code to implement this feature.
(For the undone tasks, see line 137 in UserProfileFragment.java)
> Clicking on users take you to their profile page

- code/app/src/androidTest/java/com/otmj/otmjapp/MoodEventAddEditTest.java
Changed to test if the data in the database is consistent with the de…
> Change to test in details page

- code/app/src/main/java/com/otmj/otmjapp/Adapters/UserProfilePageMoodEventAdapter.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/UserProfileFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/FollowHandler.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/UserManager.java
- code/app/src/main/res/layout/my_profile.xml
- code/app/src/main/res/layout/request_block.xml
- code/app/src/main/res/navigation/app_nav_graph.xml
- code/app/src/main/res/values/strings.xml
> Added features to profile page

- code/app/src/androidTest/java/com/otmj/otmjapp/UserProfilePageTest.java
viewMyProfilePageTest()
viewMyFollowingListTest()
viewMyFollowersListTest()
viewMyRequestsListTest()
logOutTest()
deleteMyMoodEventTest()
> 331 write UI tests for user profile page

- code/app/build.gradle.kts
- code/app/src/androidTest/java/com/otmj/otmjapp/LocationHelperTest.java
LocationHelper unit test is written in androidTest because it requires our app run to set up the the require environment
> LocationHelper test done

- code/app/src/androidTest/java/com/otmj/otmjapp/LocationHelperTest.java
- code/app/src/androidTest/java/com/otmj/otmjapp/UserManagerTests.java
Use androidTest to test userManager since userManager requires android based classes
> test for UserMananger done

- code/app/src/main/java/com/otmj/otmjapp/Fragments/FollowListFragment.java
- code/app/src/main/java/com/otmj/otmjapp/Fragments/UserProfileFragment.java
-Passed the correct userID to FollowListFragment when follower/following buttons are clicked
> Fixed Followers/Following Lists Displaying Wrong Data

- code/app/src/main/res/layout/list_screen.xml
list in the lis screen UI no longer goes beyond the bottom nav bar
> fixed minor issue with list screen UI

- code/app/build.gradle.kts
- code/app/src/androidTest/java/com/otmj/otmjapp/MoodEventManagerTest.java
- code/app/src/main/java/com/otmj/otmjapp/Helper/MoodEventsManager.java
Only the Following tests are finished:
testGetMoodEvents()
testGetPublicMoodEvents()
testGetAllMoodEvents()
> MoodEventManagerTest only finish three tests
